<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260402094500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'create type/pokemon/type_effectiveness tables (v1 model)';
    }

    public function up(Schema $schema): void
    {
        // Note: we use quoted identifiers for the `type` table as it can conflict with SQL keywords.
        $this->addSql('CREATE TABLE "type" (
            id SMALLINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            code VARCHAR(32) NOT NULL,
            label VARCHAR(64) NOT NULL,
            CONSTRAINT pk_type PRIMARY KEY (id),
            CONSTRAINT uq_type_code UNIQUE (code)
        )');

        $this->addSql('CREATE TABLE pokemon (
            id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
            source_key VARCHAR(128) NOT NULL,
            name VARCHAR(128) NOT NULL,
            primary_type_id SMALLINT NOT NULL,
            secondary_type_id SMALLINT DEFAULT NULL,
            hp SMALLINT NOT NULL,
            atk SMALLINT NOT NULL,
            "def" SMALLINT NOT NULL,
            satk SMALLINT NOT NULL,
            sdef SMALLINT NOT NULL,
            spe SMALLINT NOT NULL,
            is_active BOOLEAN NOT NULL DEFAULT true,
            CONSTRAINT pk_pokemon PRIMARY KEY (id),
            CONSTRAINT uq_pokemon_source_key UNIQUE (source_key),
            CONSTRAINT fk_pokemon_primary_type
                FOREIGN KEY (primary_type_id) REFERENCES "type"(id) ON DELETE RESTRICT,
            CONSTRAINT fk_pokemon_secondary_type
                FOREIGN KEY (secondary_type_id) REFERENCES "type"(id) ON DELETE RESTRICT,
            CONSTRAINT chk_pokemon_secondary_type
                CHECK (secondary_type_id IS NULL OR secondary_type_id <> primary_type_id),
            CONSTRAINT chk_pokemon_hp_positive CHECK (hp > 0),
            CONSTRAINT chk_pokemon_atk_positive CHECK (atk > 0),
            CONSTRAINT chk_pokemon_def_positive CHECK ("def" > 0),
            CONSTRAINT chk_pokemon_satk_positive CHECK (satk > 0),
            CONSTRAINT chk_pokemon_sdef_positive CHECK (sdef > 0),
            CONSTRAINT chk_pokemon_spe_positive CHECK (spe > 0)
        )');

        $this->addSql('CREATE TABLE type_effectiveness (
            attacking_type_id SMALLINT NOT NULL,
            defending_type_id SMALLINT NOT NULL,
            multiplier_x100 SMALLINT NOT NULL,
            CONSTRAINT pk_type_effectiveness PRIMARY KEY (attacking_type_id, defending_type_id),
            CONSTRAINT fk_type_effectiveness_attacking_type
                FOREIGN KEY (attacking_type_id) REFERENCES "type"(id) ON DELETE RESTRICT,
            CONSTRAINT fk_type_effectiveness_defending_type
                FOREIGN KEY (defending_type_id) REFERENCES "type"(id) ON DELETE RESTRICT
        )');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS type_effectiveness');
        $this->addSql('DROP TABLE IF EXISTS pokemon');
        $this->addSql('DROP TABLE IF EXISTS "type"');
    }
}

